from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')
path =  [cwd, 
         os.path.join(cwd, '../include')]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_SF32LB52_XTY_AI_THT'], CPPPATH = path)

if GetDepend('BSP_USING_BOARD_SF32LB52_XTY_AI_THT'):
    group = group + SConscript(os.path.join(cwd, '../sf32lb52-xty-ai_base/SConscript.base'), variant_dir="base", duplicate=0)

Return('group')
