from building import *

cwd = GetCurrentDir()

src = Glob('../*.c')

path =  [os.path.join(cwd, ".."), 
         os.path.join(cwd, '../../include')]

group = DefineGroup('Drivers', src, depend = [], CPPPATH = path)

Return('group')
