import os
from building import *

# Add source code
src = Glob('*.c')
src = src + Glob('./iot/*.cc') 
SrcRemove(src, 'xiaozhi.c')
group = DefineGroup('Applications', src, depend = [''])

Return('group')

